tour:
  limit_list: 3
  rating: 7
  recommended_limit: 6
  per_page: 5
  param_newest: "newest"
  short_descrip: 50
booking:
  limit: 10
  per_page: 5
  min_quantity: 1
rating:
  min_point: 0
  max_point: 10
